version: 1.0
provider:
  name: openfaas
functions:

  # ## Templates
  # python3-http-osm:
  #   lang: python3-http
  #   handler: ./templates/python3-http-osm
  #   image: ghcr.io/${OWNER:-fititnt}/python3-http-osm:${TAG:-latest}

  ## Functions
  api-proxy:
    lang: python3-http
    handler: ./function/api-proxy
    image: ghcr.io/${OWNER:-fititnt}/api-proxy:${TAG:-latest}

  api-rdf:
    lang: python3-http
    handler: ./function/api-rdf
    image: ghcr.io/${OWNER:-fititnt}/api-rdf:${TAG:-latest}

  curl:
    lang: dockerfile
    handler: ./function/curl
    image: ghcr.io/${OWNER:-fititnt}/curl:${TAG:-latest}

  overpass-proxy:
    lang: python3-http
    handler: ./function/overpass-proxy
    image: ghcr.io/${OWNER:-fititnt}/overpass-proxy:${TAG:-latest}

  sentimentanalysis:
    lang: dockerfile
    handler: ./function/sentimentanalysis
    image: ghcr.io/${OWNER:-fititnt}/sentimentanalysis:${TAG:-latest}

  # @see https://github.com/openfaas/python-flask-template/pull/39
  # @see https://github.com/openfaas/python-flask-template/blob/master/template/python3-http-debian/index.py
  # @TODO use application/zip instead of application/octet-stream
  wiki-as-base:
    # lang: python3-http
    lang: python3-http-osm
    handler: ./function/wiki-as-base
    image: ghcr.io/${OWNER:-fititnt}/wiki-as-base:${TAG:-latest}

  # @deprecated wiki-telegram-bot (use wiki-telegram-faasbot)
  wiki-telegram-bot:
    lang: python3-http
    handler: ./function/wiki-telegram-bot
    # image: wiki-telegram-bot:latest
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-bot:${TAG:-latest}

  wiki-telegram-chatbot:
    lang: python3-http
    handler: ./function/wiki-telegram-chatbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-chatbot:${TAG:-latest}

  wiki-telegram-faasbot:
    lang: python3-http
    handler: ./function/wiki-telegram-faasbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-faasbot:${TAG:-latest}

configuration:
  templates:
    - name: python3-http
      source: https://github.com/openfaas/python-flask-template

    # This is small fork to add binary output for zip files
    - name: python3-http-osm
      source: https://github.com/fititnt/openstreetmap-serverless-functions
