version: 1.0
provider:
  name: openfaas
functions:
  api-proxy:
    lang: python3-http
    handler: ./function/api-proxy
    image: ghcr.io/${OWNER:-fititnt}/api-proxy:${TAG:-latest}

  api-rdf:
    lang: python3-http
    handler: ./function/api-rdf
    image: ghcr.io/${OWNER:-fititnt}/api-rdf:${TAG:-latest}

  curl:
    lang: dockerfile
    handler: ./function/curl
    image: ghcr.io/${OWNER:-fititnt}/curl:${TAG:-latest}

  overpass-proxy:
    lang: python3-http
    handler: ./function/overpass-proxy
    image: ghcr.io/${OWNER:-fititnt}/overpass-proxy:${TAG:-latest}

  sentimentanalysis:
    lang: dockerfile
    handler: ./function/sentimentanalysis
    image: ghcr.io/${OWNER:-fititnt}/sentimentanalysis:${TAG:-latest}

  wiki-as-base:
    lang: python3-http
    handler: ./function/wiki-as-base
    # image: wiki-as-base:latest
    image: ghcr.io/${OWNER:-fititnt}/wiki-as-base:${TAG:-latest}

  # @deprecated wiki-telegram-bot (use wiki-telegram-faasbot)
  wiki-telegram-bot:
    lang: python3-http
    handler: ./function/wiki-telegram-bot
    # image: wiki-telegram-bot:latest
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-bot:${TAG:-latest}

  wiki-telegram-chatbot:
    lang: python3-http
    handler: ./function/wiki-telegram-chatbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-chatbot:${TAG:-latest}

  wiki-telegram-faasbot:
    lang: python3-http
    handler: ./function/wiki-telegram-faasbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-faasbot:${TAG:-latest}

# configuration:
#   templates:
#     - name: dockerfile
#     - name: python3-http
#       source: https://github.com/openfaas/python-flask-template
