version: 1.0
provider:
  name: openfaas
functions:
  # ## Templates
  # python3-http-osm:
  #   lang: python3-http
  #   handler: ./templates/python3-http-osm
  #   image: ghcr.io/${OWNER:-fititnt}/python3-http-osm:${TAG:-latest}

  ## Functions
  api-proxy:
    lang: python3-http
    handler: ./function/api-proxy
    image: ghcr.io/${OWNER:-fititnt}/api-proxy:${TAG:-latest}

  api-rdf:
    lang: python3-http
    handler: ./function/api-rdf
    image: ghcr.io/${OWNER:-fititnt}/api-rdf:${TAG:-latest}

  curl:
    lang: dockerfile
    handler: ./function/curl
    image: ghcr.io/${OWNER:-fititnt}/curl:${TAG:-latest}

  okmapabot:
    lang: python3-http
    # lang: python3-http-osm
    handler: ./function/okmapabot
    image: ghcr.io/${OWNER:-fititnt}/okmapabot:${TAG:-latest}
    environment:
      # TELEGRAM_BOT_TOKEN: # Unless testing, use from secret file in production
      TELEGRAM_BOT_TOKEN_FILE: secret-okmapabot-telegram-token
      TELEGRAM_BOT_APISECRET_FILE: secret-okmapabot-telegram-apisecret
      TELEGRAM_BOT_NAME: OkMapaBot
      FAAS_BACKEND: https://osm-faas.etica.ai/function/
      FAAS_ALLOWED: ""
      RIVE_WIKIASBASE_BRAIN_0: ""
      RIVE_WIKIASBASE_BRAIN_1: ""
      RIVE_WIKIASBASE_BRAIN_2: ""
      RIVE_FILES_0: "https://raw.githubusercontent.com/fititnt/openstreetmap-tags-to-rivescript/main/example/brain/osm-tagging-pt.rive|https://raw.githubusercontent.com/fititnt/openstreetmap-tags-to-rivescript/main/example/brain/osm-tagging-reverse_pt.rive"
      RIVE_FILES_1: ""
      RIVE_FILES_2: ""

  overpass-proxy:
    lang: python3-http
    handler: ./function/overpass-proxy
    image: ghcr.io/${OWNER:-fititnt}/overpass-proxy:${TAG:-latest}

  sentimentanalysis:
    lang: dockerfile
    handler: ./function/sentimentanalysis
    image: ghcr.io/${OWNER:-fititnt}/sentimentanalysis:${TAG:-latest}

  # @see https://github.com/openfaas/python-flask-template/pull/39
  # @see https://github.com/openfaas/python-flask-template/blob/master/template/python3-http-debian/index.py
  # @TODO use application/zip instead of application/octet-stream
  wiki-as-base:
    # lang: python3-http
    lang: python3-http-osm
    handler: ./function/wiki-as-base
    image: ghcr.io/${OWNER:-fititnt}/wiki-as-base:${TAG:-latest}

  # @deprecated wiki-telegram-bot (use wiki-telegram-faasbot)
  wiki-telegram-bot:
    lang: python3-http
    handler: ./function/wiki-telegram-bot
    # image: wiki-telegram-bot:latest
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-bot:${TAG:-latest}

  wiki-telegram-chatbot:
    lang: python3-http
    # lang: python3-http-osm
    handler: ./function/wiki-telegram-chatbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-chatbot:${TAG:-latest}

  wiki-telegram-faasbot:
    lang: python3-http
    handler: ./function/wiki-telegram-faasbot
    image: ghcr.io/${OWNER:-fititnt}/wiki-telegram-faasbot:${TAG:-latest}

configuration:
  templates:
    - name: python3-http
      source: https://github.com/openfaas/python-flask-template

    # This is small fork to add binary output for zip files
    - name: python3-http-osm
      source: https://github.com/fititnt/openstreetmap-serverless-functions
